### ISSUE TITLE
Release new image with current hugo

### ISSUE THREAD

**Issue by vbrandl** [drone-plugins/drone-hugo#8]
Currently, the image contains hugo v0.40.2 but the latest version is v0.46.
I'm using a theme that requires at least v0.44.
Could you please push an updated image, containing the latest hugo version?

**Comment by tboerger** [comment]
There will be a new version of this plugin soon where you can control the used hugo version with a custom flag.

**Comment by cbrgm** [comment]
We'll improve a few things before the new version is merged into the master branch. Will be merged soon.

**Comment by vtolstov** [comment]
gentle ping..

**Comment by vtolstov** [comment]
I'm waiting for --minify flag..

**Comment by sofixa** [comment]
@cbrgm the new version seems to be merged but the container isn't be published, and the plugin docs still point to the old container (which uses a pretty outdated version, 0.40.2).

**Comment by cbrgm** [comment]
@sofixa Thanks for your hint. Maybe @tboerger can help setting the docker secrets, so the image can be pushed to dockerhub?

**Comment by tboerger** [comment]
@cbrgm build failed, could you add the manifests.tmpl? Than we got an updated version.

**Comment by cbrgm** [comment]
@sofixa new Images have been pushed. Thanks to @tboerger for adding the secrets configuration.

I'm working on new plugin flags to support some of the recently introduced hugo args e.g. `--minify` flag, ...

**Comment by sofixa** [comment]
@cbrgm Great! 

However, the docs are still pointing to the old image :
https://github.com/drone/drone-plugin-index/blob/master/content/cbrgm/drone-hugo/index.md

Are drone-plugins/hugo and cbrgm/drone-hugo the same image?

Adrian

**Comment by bradrydzewski** [comment]
I suggest we revise the approach and use the hugo version number as the docker tag, which would correspond to the version of hugo running in the plugin, for example `plugins/hugo:0.53`. Downloading the binary every time the step executes is inefficient, and I'm struggling to justify having an official plugin for this when you consider the following:

```
- name: hugo
  image: monachus/hugo:v0.53
  commands:
  - hugo --buildDrafts --buildExpired --buildFuture
```

To be fair I do think there is value in having an official hugo plugin because hugo does not ship an official Docker image. But since this is part of the official plugins organization I want to see the plugin optimized a little bit :)

**Comment by cbrgm** [comment]
I had the same discussion with @tboerger  when we thought about how to best version the plugin. Originally the image tag was used according to the hugo version, exactly as described in the example above. 

The decision for the download was made because otherwise we would have to provide an image for each Hugo version. Also because Drone users don't have to wait for the plugin to be updated when they release a new version of Hugo. That's why we chose a middle course. The plugin comes with a certain hugo version, so no download is necessary. the `hugo_version` tag can simply be omitted. At the same time the user can choose his own hugo version, which will be downloaded before running.  I'm willing to reconsider the whole thing.  Thomas, what do you think?

**Comment by tboerger** [comment]
I'm personally fine with the current behavior, as already described Hugo gets downloaded only if somebody enforces a specific version, and also only if it doesn't match the shipped version. IMHO it doesn't scale well to tag the plugin based on the Hugo version, beside that it's hard to add some kind of breaking change if the tags are just following Hugo versioning.

**Comment by jacksgt** [comment]
Hi everyone!

I think there is a real case to be made for an "officially endorsed" Hugo plugin for Drone. It gives newcomers an easy entry and at the same time provides a sense of stability (instead of having to search and downloading a random image from DockerHub).

I'd prefer the solution where Drone has a "native" Hugo plugin (i..e not downloading it on the fly), because 
* a) I think that is very wasteful (especially with the size of Go binaries), tagged with the same version number (e.g. `plugins/hugo:v0.54`) so that users can select their version, roll back etc. 
* b) I don't expect it to be a problem to keep up with the Hugo releases. It is very easy for anyone to just submit a Pull Request updating the version string (in this repo).

**Comment by tboerger** [comment]
Maybe somebody wants to bump the bundled hugo version? Than we could finally close this PR until we change the behavior for shipped hugo versions.
